[package]
edition = "2021"
name = "{{project-name}}"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.8.0"{% if nightly == "Yes" %}, features = ["nightly"]{% endif %} }
leptos_router = { version = "0.8.0"{% if nightly == "Yes" %}, features = ["nightly"]{% endif %} }
axum = { version = "0.8.0", optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
leptos_axum = { version = "0.8.0", optional = true }
leptos_meta = { version = "0.8.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
wasm-bindgen = { version = "0.2.106", optional = true }

[features]
hydrate = ["leptos/hydrate", "dep:console_error_panic_hook", "dep:wasm-bindgen"]
ssr = ["dep:axum", "dep:tokio", "dep:leptos_axum", "leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]

[profile.wasm-release]
codegen-units = 1
inherits = "release"
lto = true
opt-level = 'z'
panic = "abort"

[package.metadata.leptos]
assets-dir = "public"
bin-default-features = false
bin-features = ["ssr"]
browserquery = "defaults"
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"
env = "DEV" # "PROD"
lib-default-features = false
lib-features = ["hydrate"]
lib-profile-release = "wasm-release"
output-name = "{{project-name}}"
reload-port = 3001
site-addr = "127.0.0.1:3000"
site-pkg-dir = "pkg"
site-root = "target/site"
style-file = "style/main.css"
